[package]
name = "database"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "1.0"
log = "0.4"
env_logger = "0.11.5"
crc32fast = "1.4.2"
threadpool = "1.8.1"
bincode = "1.3.3"
serde = { version = "1.0", features = ["derive"] }

[dev-dependencies]
tempfile = "3.8"
